import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'ar' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: any;
  dir: 'rtl' | 'ltr';
}

const translations = {
  ar: {
    common: {
      appName: 'لميس للمنظفات',
      appDesc: 'نظام إدارة المخزون',
      copyright: '© 2025 شركة لميس. جميع الحقوق محفوظة.',
      version: 'الإصدار 1.2.0',
      loading: 'جاري التحميل...',
      success: 'تمت العملية بنجاح',
      error: 'حدث خطأ',
      confirmDelete: 'هل أنت متأكد من الحذف؟',
      save: 'حفظ',
      cancel: 'إلغاء',
      delete: 'حذف',
      edit: 'تعديل',
      print: 'طباعة',
      export: 'تصدير',
      import: 'استيراد',
      search: 'بحث...',
      noData: 'لا توجد بيانات',
      required: 'مطلوب',
      optional: 'اختياري',
      unit: 'الوحدة',
      price: 'السعر',
      quantity: 'الكمية',
      date: 'التاريخ',
      actions: 'إجراءات',
      image: 'الصورة',
      name: 'الاسم',
    },
    sidebar: {
      dashboard: 'لوحة التحكم',
      inventory: 'المخزون',
      stockOut: 'إخراج قطع',
      newItem: 'تعريف قطعة جديدة',
      history: 'سجل العمليات',
      logout: 'تسجيل الخروج',
    },
    login: {
      welcomeBack: 'مرحباً بعودتك!',
      joinUs: 'انضم إلينا اليوم',
      systemName: 'نظام إدارة مستودعات الصيانة في شركة لميس لصناعة المنظفات',
      loginTitle: 'تسجيل الدخول',
      signupTitle: 'إنشاء حساب جديد',
      enterDetails: 'أدخل بياناتك للمتابعة',
      googleBtn: 'المتابعة باستخدام Google',
      or: 'أو',
      fullName: 'الاسم الكامل',
      email: 'البريد الإلكتروني',
      password: 'كلمة المرور',
      haveAccount: 'لديك حساب بالفعل؟',
      noAccount: 'ليس لديك حساب؟',
      createAccount: 'إنشاء حساب جديد',
      signIn: 'تسجيل الدخول',
      errorCredentials: 'البريد الإلكتروني أو كلمة المرور غير صحيحة',
      errorExists: 'هذا البريد الإلكتروني مسجل مسبقاً',
      tryAdmin: 'جرب: admin@lamis.com / 123456',
    },
    dashboard: {
      title: 'لوحة التحكم التحليلية',
      kpiTitle: 'مؤشرات الأداء الرئيسية (KPIs)',
      totalItems: 'إجمالي القطع المعرفة',
      totalStock: 'إجمالي المخزون (كمية)',
      lowStock: 'قطع منخفضة المخزون',
      totalValue: 'قيمة المخزون التقديرية',
      stockDistribution: 'توزيع المخزون حسب الفئة',
      topStock: 'مستويات المخزون (أعلى 10 قطع)',
      topMovers: 'أكثر القطع حركة',
      recentTrx: 'آخر العمليات',
      alertTitle: 'تنبيه: انخفاض المخزون',
      alertBody: 'يوجد قطع وصلت أو انخفضت عن الحد الأدنى للمخزون.',
      current: 'المتوفر',
      min: 'الحد الأدنى',
      category: 'فئة',
      table: {
        date: 'التاريخ',
        type: 'النوع',
        item: 'اسم القطعة',
        qty: 'الكمية',
        supervisor: 'المسؤول',
      },
      types: {
        in: 'إدخال',
        out: 'إخراج',
        new: 'تعريف جديد',
      },
      kpis: {
        serviceLevel: 'مستوى الخدمة (Service Level)',
        cycleCount: 'اكتمال الجرد الدوري',
        accuracy: 'دقة السجلات',
        nonUsed: 'المواد غير المستخدمة',
        obsolete: 'المواد الراكدة (Obsolete)',
        bom: 'اكتمال بيانات BOM',
        abcz: 'تصنيف ABCZ',
      }
    },
    newItem: {
      title: 'تعريف قطعة جديدة',
      cameraBtn: 'صورة القطعة (اختياري)',
      openCamera: 'فتح الكاميرا',
      capture: 'التقاط',
      noImage: 'لا توجد صورة',
      autoId: 'رقم القطعة (تلقائي)',
      generated: '-- سيتم توليده --',
      itemName: 'اسم القطعة',
      initialQty: 'الكمية الأولية',
      shelf: 'رقم الرف (اختياري)',
      specs: 'المواصفات الفنية',
      minLevel: 'الحد الأدنى (اختياري)',
      maxLevel: 'الحد الأعلى (اختياري)',
      unitPrice: 'سعر الوحدة (اختياري)',
      itemType: 'نوع القطعة',
      itemCategory: 'فئة القطعة',
      submitBtn: 'حفظ القطعة في النظام',
      successMsg: 'تم إضافة القطعة بنجاح',
      validationMinMax: 'الحد الأدنى يجب أن يكون أصغر من الحد الأعلى',
    },
    stockOut: {
      title: 'إخراج قطع من المخزون',
      tabScanner: 'ماسح الباركود',
      tabManual: 'بحث يدوي',
      scanTitle: 'مسح الباركود',
      cameraStart: 'اضغط لتشغيل الكاميرا',
      cameraStop: 'إيقاف',
      simulate: 'محاكاة قراءة باركود (تجريبي)',
      manualTitle: 'بحث عن قطعة',
      searchPlaceholder: 'ابحث بالاسم، الرقم، أو الوصف...',
      noResults: 'لا توجد نتائج',
      selectMsg: 'قم باختيار أو مسح قطعة لإظهار التفاصيل',
      detailsTitle: 'تفاصيل القطعة',
      available: 'متوفر',
      unavailable: 'غير متوفر',
      currentQty: 'الكمية الحالية',
      receiver: 'اسم المستلم',
      supervisor: 'اسم المسؤول',
      location: 'مكان التركيب',
      reqQty: 'العدد المطلوب',
      delDate: 'تاريخ التسليم',
      confirmBtn: 'تأكيد إخراج القطعة',
      qtyError: 'الكمية المطلوبة أكبر من المتوفر',
      successMsg: 'تم إخراج القطعة بنجاح',
    },
    inventoryList: {
      title: 'قائمة المخزون الكاملة',
      printSelected: 'طباعة المحدد',
      searchPlaceholder: 'بحث باسم القطعة أو الرقم...',
      filterAll: 'كل الفئات',
      filterA: 'فئة A',
      filterB: 'فئة B',
      filterC: 'فئة C',
      filterZ: 'فئة Z',
      table: {
        def: 'التعريف',
        typeCat: 'النوع / الفئة',
        loc: 'الموقع',
        specs: 'المواصفات',
      },
      importSuccess: 'تم استيراد القطع بنجاح',
    },
    history: {
      title: 'سجل العمليات',
      exportBtn: 'تصدير إلى Excel',
      table: {
        id: 'رقم العملية',
        dateTime: 'التاريخ والوقت',
        type: 'نوع العملية',
        item: 'القطعة',
        qty: 'الكمية',
        details: 'التفاصيل',
      },
      types: {
        new: 'تعريف جديد',
        out: 'إخراج مخزني',
        in: 'إدخال',
      },
      labels: {
        supervisor: 'المسؤول',
        receiver: 'المستلم',
        location: 'الموقع',
        date: 'تاريخ التسليم',
        signed: 'تم التوقيع',
      },
      empty: 'لا توجد عمليات مسجلة حتى الآن',
    }
  },
  en: {
    common: {
      appName: 'Lamis Detergents',
      appDesc: 'Inventory Management System',
      copyright: '© 2025 Lamis Co. All rights reserved.',
      version: 'Version 1.2.0',
      loading: 'Loading...',
      success: 'Operation Successful',
      error: 'An Error Occurred',
      confirmDelete: 'Are you sure you want to delete?',
      save: 'Save',
      cancel: 'Cancel',
      delete: 'Delete',
      edit: 'Edit',
      print: 'Print',
      export: 'Export',
      import: 'Import',
      search: 'Search...',
      noData: 'No Data',
      required: 'Required',
      optional: 'Optional',
      unit: 'Unit',
      price: 'Price',
      quantity: 'Quantity',
      date: 'Date',
      actions: 'Actions',
      image: 'Image',
      name: 'Name',
    },
    sidebar: {
      dashboard: 'Dashboard',
      inventory: 'Inventory',
      stockOut: 'Stock Out',
      newItem: 'New Item',
      history: 'History',
      logout: 'Logout',
    },
    login: {
      welcomeBack: 'Welcome Back!',
      joinUs: 'Join Us Today',
      systemName: 'Maintenance Warehouse Management System at Lamis Detergents Co.',
      loginTitle: 'Login',
      signupTitle: 'Create Account',
      enterDetails: 'Enter your details to continue',
      googleBtn: 'Continue with Google',
      or: 'OR',
      fullName: 'Full Name',
      email: 'Email Address',
      password: 'Password',
      haveAccount: 'Already have an account?',
      noAccount: 'Don\'t have an account?',
      createAccount: 'Sign Up',
      signIn: 'Sign In',
      errorCredentials: 'Invalid email or password',
      errorExists: 'Email already registered',
      tryAdmin: 'Try: admin@lamis.com / 123456',
    },
    dashboard: {
      title: 'Analytical Dashboard',
      kpiTitle: 'Key Performance Indicators (KPIs)',
      totalItems: 'Total Items Defined',
      totalStock: 'Total Stock Quantity',
      lowStock: 'Low Stock Items',
      totalValue: 'Est. Stock Value',
      stockDistribution: 'Stock Distribution by Category',
      topStock: 'Top 10 Stock Levels',
      topMovers: 'Top Moving Items',
      recentTrx: 'Recent Transactions',
      alertTitle: 'Alert: Low Stock',
      alertBody: 'There are items at or below minimum stock level.',
      current: 'Current',
      min: 'Min',
      category: 'Cat',
      table: {
        date: 'Date',
        type: 'Type',
        item: 'Item Name',
        qty: 'Qty',
        supervisor: 'Supervisor',
      },
      types: {
        in: 'IN',
        out: 'OUT',
        new: 'NEW',
      },
      kpis: {
        serviceLevel: 'Service Level',
        cycleCount: 'Cycle Counting Completion',
        accuracy: 'Inventory Accuracy',
        nonUsed: 'Non-Used Materials',
        obsolete: 'Obsolete Materials',
        bom: 'BOM Completion',
        abcz: 'ABCZ Completion',
      }
    },
    newItem: {
      title: 'Define New Item',
      cameraBtn: 'Item Image (Optional)',
      openCamera: 'Open Camera',
      capture: 'Capture',
      noImage: 'No Image',
      autoId: 'Item ID (Auto)',
      generated: '-- Generated --',
      itemName: 'Item Name',
      initialQty: 'Initial Quantity',
      shelf: 'Shelf No. (Optional)',
      specs: 'Technical Specifications',
      minLevel: 'Min Level (Optional)',
      maxLevel: 'Max Level (Optional)',
      unitPrice: 'Unit Price (Optional)',
      itemType: 'Item Type',
      itemCategory: 'Item Category',
      submitBtn: 'Save Item to System',
      successMsg: 'Item added successfully',
      validationMinMax: 'Minimum level must be less than Maximum level',
    },
    stockOut: {
      title: 'Stock Out / Withdraw',
      tabScanner: 'Barcode Scanner',
      tabManual: 'Manual Search',
      scanTitle: 'Scan Barcode',
      cameraStart: 'Tap to Start Camera',
      cameraStop: 'Stop',
      simulate: 'Simulate Scan (Demo)',
      manualTitle: 'Search Item',
      searchPlaceholder: 'Search by name, ID, or desc...',
      noResults: 'No results found',
      selectMsg: 'Select or scan an item to view details',
      detailsTitle: 'Item Details',
      available: 'Available',
      unavailable: 'Unavailable',
      currentQty: 'Current Qty',
      receiver: 'Receiver Name',
      supervisor: 'Supervisor Name',
      location: 'Installation Location',
      reqQty: 'Required Qty',
      delDate: 'Delivery Date',
      confirmBtn: 'Confirm Stock Out',
      qtyError: 'Required quantity exceeds stock',
      successMsg: 'Stock out processed successfully',
    },
    inventoryList: {
      title: 'Full Inventory List',
      printSelected: 'Print Selected',
      searchPlaceholder: 'Search name or ID...',
      filterAll: 'All Categories',
      filterA: 'Category A',
      filterB: 'Category B',
      filterC: 'Category C',
      filterZ: 'Category Z',
      table: {
        def: 'Definition',
        typeCat: 'Type/Cat',
        loc: 'Location',
        specs: 'Specs',
      },
      importSuccess: 'Items imported successfully',
    },
    history: {
      title: 'Transaction History',
      exportBtn: 'Export to Excel',
      table: {
        id: 'Trx ID',
        dateTime: 'Date & Time',
        type: 'Type',
        item: 'Item',
        qty: 'Qty',
        details: 'Details',
      },
      types: {
        new: 'New Item',
        out: 'Stock Out',
        in: 'Stock In',
      },
      labels: {
        supervisor: 'Supervisor',
        receiver: 'Receiver',
        location: 'Location',
        date: 'Delivery',
        signed: 'Signed',
      },
      empty: 'No transactions recorded yet',
    }
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ar');

  useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = translations[language];
  const dir = language === 'ar' ? 'rtl' : 'ltr';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
